### ISSUE TITLE
max_demand from Enum seems wrong

### ISSUE THREAD

**Issue by ijcd** [elixir-lang/flow#33]
I'm not sure if this is a bug or a misunderstanding on my part. I've narrowed it down to this simple example which just prints out the demand received by the source of a `Flow`:

```
defmodule FlowBug do
  use GenStage

  def start_link(name) do
    GenStage.start_link(__MODULE__, name)
  end

  def init(name) do
    IO.puts("#{name} init")
    {:producer, name}
  end

  def handle_demand(demand, name) do
    IO.puts("#{name} DEMAND: #{demand}")
    {:noreply, [], name}
  end
end
```

If I use `Flow.run()`, the demand is `1`, as I would expect:

```
iex(1)> {:ok, pid_flow} = FlowBug.start_link("Flow.run")
Flow.run init
{:ok, #PID<0.162.0>}
iex(2)> pid_flow |> Flow.from_stage(stages: 1, max_demand: 1) |> Flow.run
Flow.run DEMAND: 1
```

However, if I use an `Enum` of any sort (I often do this from `iex` when I am trying to debug things), `max_demand` does not seem to be respected:

```
iex(1)> {:ok, pid_enum} = FlowBug.start_link("Enum.to_list")
Enum.to_list init
{:ok, #PID<0.150.0>}
iex(2)> pid_enum |> Flow.from_stage(max_demand: 1) |> Enum.to_list
Enum.to_list DEMAND: 1000
```

I am using Flow for IO-bound things, like calling out to other services during web scraping, etc. I need the back-pressure features more than the parallelism for this. In debugging, I often will do this:

```
flow |> Stream.take(n) |> Enum.to_list
```

Just to get things working... I think this used to work fine, but now it seems different (or never worked).

**Comment by josevalim** [comment]
This is a little bit tricky because I believe Flow never allowed you to control the parameters of `Enum.to_list`. When you specify `max_demand: 1` in `pid_enum |> Flow.from_stage(max_demand: 1) |> Enum.to_list`, you are specifying how the following stages in flow will consume the previous stage, not `Enum.to_list`. The reason why `Flow.run` works is because it starts intermediate stages to consume the whole flow, while `Enum.to_list` does not because in this particular case the intermediate stages are not necessary.

To understand why this an issue, just take a more complex flow:

    stage
    |> Flow.from_stage(max_demand: 1)
    |> Flow.map(...)
    |> Flow.partition(max_demand: 10)
    |> Flow.reduce(...)
    |> Enum.to_list

In the example above, you have mapper stages consuming from the initial stage with demand of 1, then reducer stages consuming the mapper stages with demand of 10. Notice how, every time we specify max_demand, we are configuring how to consume the operations that come before, never the operation that comes after. Nowhere we are able to specify how `Enum.to_list` will consume elements.

If your example is actually how you are using Flow in production, then you can skip flow altogether and consume directly from the stage by using `GenStage.stream/2`. If you actually have a more complex flow, please post it here so we can discuss how to properly customize Enum.to_list.

Thanks!

**Comment by ijcd** [comment]
Ah! I see what my issues is -- and yes, it's me -- it is that my mental model wasn't quite right. I was confusing `max_demand` for a GenStage with the `max_demand` for a `Flow`, which, while related, are slightly different. I was seeing each call to `Flow` as a `GenStage` and so was assuming that calling `Flow.from_stage` or similar created a `GenStage` that would gate the `max_demand`. I see know that it is just constructing some set of `GenStage`s, the topology of which depends on what is being wired.

I am not using `|> Enum.to_list` in production like this. I stumbled on this while testing bits of code in `iex>` and got confused.

The use case for `Flow` that I'm working on now is constructing flows of data from external sources to internal processing. I am using these parts of `Flow` to bound the number of simultaneous calls to an external API, for example. With `Stream` I would need to create/use pools, etc. While that would be more sophisticated, this is a simpler way to quickly get something composable that mostly works. I'll iterate on pools/backoff to the APIs later (or rather think that should be part of the API-call task).

`Flow` also allows me to enable/disable flows and redirect source->sink mappings by playing with `sync_subscribe` with a simple sort of scheduler.

My current sources are custom `GenServer`s wrapping the APIs. My sinks are `ConsumerSupervisor`s which bound the number of active things being processed. The `Flow` provides a nice backpressure-based way to consume the APIs and process the data.
